plugins {
    id 'fabric-loom' version '1.7.4'
    id 'maven-publish'
}

group = project.property('mod_group')
version = project.property('mod_version')

base {
    archivesName = project.property('mod_id')
}

repositories {
    maven {
        url = uri('https://maven.fabricmc.net/')
    }

    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.property('minecraft_version')}"
    mappings "net.fabricmc:yarn:${project.property('yarn_mappings')}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.property('loader_version')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.property('fabric_version')}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
}

tasks.named('build') {
    dependsOn tasks.named('remapJar')
}

tasks.named('jar') {
    from('LICENSE') {
        rename { fileName ->
            "${fileName}_${project.property('mod_id')}"
        }
    }
}

tasks.named('remapJar') {
    archiveClassifier.set('')
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
