pluginManagement {
    repositories {
        // Explicitly tells Gradle where to locate the Fabric-Loom developer binaries
        maven { url = "https://fabricmc.net" }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
}

rootProject.name = 'turbowarp-x-mincraft'



