pluginManagement {
    repositories {
        // FIXED: Complete official URL block allowing Gradle to locate the loom compiler
        maven {
            name = "Fabric"
            url = "https://fabricmc.net"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
}

rootProject.name = 'turbowarp-x-mincraft'


